---

# https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
# We don't need sudo here because we only create some files in /tmp

sudo: no
language: python
python: "2.7"

env:
  global:
  matrix:
    - ANSIBLE_VERSION="2.0.0.2"  PASSLIB_VERSION="1.7.1"  TEST_ASA=1
    - ANSIBLE_VERSION="2.1.4.0"  PASSLIB_VERSION="1.7.1"  TEST_ASA=1
    - ANSIBLE_VERSION="2.2.3.0"  PASSLIB_VERSION="1.7.1"  TEST_ASA=1
    - ANSIBLE_VERSION="2.3.0.0"  PASSLIB_VERSION="1.7.1"  TEST_ASA=1
    - ANSIBLE_VERSION="2.0.0.2"  PASSLIB_VERSION="1.7"    TEST_ASA=1
    - ANSIBLE_VERSION="2.1.4.0"  PASSLIB_VERSION="1.7"    TEST_ASA=1
    - ANSIBLE_VERSION="2.2.3.0"  PASSLIB_VERSION="1.7"    TEST_ASA=1
    - ANSIBLE_VERSION="2.3.0.0"  PASSLIB_VERSION="1.7"    TEST_ASA=1
    - ANSIBLE_VERSION="2.0.0.2"  PASSLIB_VERSION="1.6.5"  TEST_ASA=0
    - ANSIBLE_VERSION="2.1.4.0"  PASSLIB_VERSION="1.6.5"  TEST_ASA=0
    - ANSIBLE_VERSION="2.2.3.0"  PASSLIB_VERSION="1.6.5"  TEST_ASA=0
    - ANSIBLE_VERSION="2.3.0.0"  PASSLIB_VERSION="1.6.5"  TEST_ASA=0
    - ANSIBLE_VERSION="2.0.0.2"  PASSLIB_VERSION="1.6"    TEST_ASA=0
    - ANSIBLE_VERSION="2.1.4.0"  PASSLIB_VERSION="1.6"    TEST_ASA=0
    - ANSIBLE_VERSION="2.2.3.0"  PASSLIB_VERSION="1.6"    TEST_ASA=0
    - ANSIBLE_VERSION="2.3.0.0"  PASSLIB_VERSION="1.6"    TEST_ASA=0

install:
  - pip install --upgrade pip setuptools packaging
  - pip install ansible==$ANSIBLE_VERSION passlib==$PASSLIB_VERSION

script:
  - echo "[defaults]"      > ansible.cfg
  - echo "roles_path=../" >> ansible.cfg
  - ansible-playbook -i tests/inventory tests/test.yml -e "TEST_ASA=$TEST_ASA" --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml -e "TEST_ASA=$TEST_ASA" -vvvv --connection=local
  - cat /tmp/ciscohash*
  - grep '^\$1\$' /tmp/ciscohash5 || exit 1
  - grep '[0-9A-F]' /tmp/ciscohash7 || exit 1
  - test $TEST_ASA -eq 0 || grep 'NuLKvvWGg.x9HEKO' /tmp/ciscohashasa || exit 1
  - grep 'NuLKvvWGg.x9HEKO' /tmp/ciscohashpix || exit 1
  - test $TEST_ASA -eq 0 || grep 'A5XOy94YKDPXCo7U' /tmp/ciscohashasa_user || exit 1
  - grep 'A5XOy94YKDPXCo7U' /tmp/ciscohashpix_user || exit 1
